name: Linux Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0.3'

    - name: Install TDLib dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake gperf libssl-dev zlib1g-dev pkg-config git

    - name: Cache TDLib build
      id: cache-tdlib
      uses: actions/cache@v4
      with:
        path: /usr/local
        key: tdlib-${{ runner.os }}-${{ hashFiles('.github/workflows/linux-build.yml') }}

    - name: Build and install TDLib
      if: steps.cache-tdlib.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/tdlib/td.git /tmp/td
        cd /tmp/td
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
        cmake --build . -j$(nproc)
        sudo cmake --install .
        sudo ldconfig

    - name: Verify TDLib installation
      run: |
        ldconfig -p | grep tdjson
        pkg-config --modversion tdjson || echo "WARNING: pkg-config cannot find tdjson"

    - name: Clean SwiftPM build cache (workaround for hangs)
      run: |
        rm -rf .build
        echo "Cleared .build directory to prevent SwiftPM hangs"

    - name: Build project
      run: |
        swift build 2>&1 | tail -50
      timeout-minutes: 5

    - name: Run tests
      run: |
        swift test 2>&1 | head -100
      timeout-minutes: 5

    - name: Check binary exists
      run: |
        ls -lh .build/debug/tg-client
        file .build/debug/tg-client
